import type { CatalogProduct } from "./types";

const baseCompliance = {
  manufacturer_name: "[LEGAL ENTITY PLACEHOLDER]",
  manufacturer_address: "[ADDRESS PLACEHOLDER], Deutschland",
  manufacturer_email: "compliance@PLACEHOLDER.domain",
  batch_or_version: "batch-01",
  material: "PLA / PETG (see variant)",
  warnings: ["Nicht für Kinder unter 3 Jahren geeignet, wenn Kleinteile vorhanden."],
  age_recommendation: "14+",
  safety_information: "Dekoration / Accessoire — kein zertifiziertes Spielzeug.",
  compliance_status: "IN_REVIEW" as const,
  documentation: ["production/stl/masters"],
};

type Seed = {
  id: string;
  slug: string;
  sku: string;
  category_id: string;
  subcategory_id: string;
  group: CatalogProduct["group"];
  vibes: CatalogProduct["vibes"];
  name: { de: string; en: string };
  description: { de: string; en: string };
  why: { de: string; en: string };
  fields: CatalogProduct["personalization_fields"];
  personalizable: boolean;
  dims: string;
  weight_g: number;
  grams: number;
  minutes: number;
  price: number;
  persoPrice: number;
  product_class: CatalogProduct["compliance"]["product_class"];
  drop?: CatalogProduct["drop_label"];
  hex: string;
  colorName: string;
  colorCode: string;
  material?: string;
  mode?: "IN_STOCK" | "PRINT_ON_DEMAND";
  images?: string[];
  included?: { de: string; en: string };
};

/** 20 filament colors for name keychain (base tone; text contrast printed white/ink). */
const KEYCHAIN_COLORS: { code: string; name: string; hex: string }[] = [
  { code: "VIO", name: "Violet", hex: "#6B2D9B" },
  { code: "YEL", name: "Feast Yellow", hex: "#FFE600" },
  { code: "INK", name: "Ink Black", hex: "#0B0B0F" },
  { code: "WHT", name: "Jade White", hex: "#F5F5F0" },
  { code: "COR", name: "Coral", hex: "#FF5A3C" },
  { code: "PNK", name: "Hot Pink", hex: "#FF2D8A" },
  { code: "RED", name: "Signal Red", hex: "#E10600" },
  { code: "ORG", name: "Orange Pop", hex: "#FF7A00" },
  { code: "LIM", name: "Acid Lime", hex: "#C8FF3D" },
  { code: "GRN", name: "Forest", hex: "#1F7A3A" },
  { code: "TEA", name: "Teal", hex: "#1F8A7A" },
  { code: "CYA", name: "Cyan", hex: "#00C2D1" },
  { code: "BLU", name: "Royal Blue", hex: "#1E4DD8" },
  { code: "NAV", name: "Navy", hex: "#14213D" },
  { code: "PUR", name: "Grape", hex: "#7B61FF" },
  { code: "LAV", name: "Lavender", hex: "#C5A3FF" },
  { code: "BRN", name: "Chocolate", hex: "#5C3A21" },
  { code: "BEG", name: "Sand Beige", hex: "#E8E4DA" },
  { code: "SLV", name: "Silver Grey", hex: "#A8ADB5" },
  { code: "GLD", name: "Gold", hex: "#D4A017" },
];

function variantsForSeed(
  s: Seed,
  stock: number,
): CatalogProduct["variants"] {
  if (s.slug === "name-keychain") {
    return KEYCHAIN_COLORS.map((c, i) => ({
      id: `v-${s.id}-${c.code.toLowerCase()}`,
      master_sku: `${s.sku}-${c.code}-M`,
      size: "M" as const,
      color: {
        id: `c-key-${c.code.toLowerCase()}`,
        color_name: c.name,
        hex: c.hex,
        filament_sku: `FIL-PLA-${c.code}-01`,
        printer_profile: "pla-standard-0.2",
        stock_material: "PLA",
      },
      price_cents: s.price,
      personalization_price_cents: s.persoPrice,
      available_stock: i < 8 ? stock : 0,
      production_capacity: 40,
      safety_stock: 5,
      mode: (i < 8 ? s.mode || "PRINT_ON_DEMAND" : "PRINT_ON_DEMAND") as
        | "IN_STOCK"
        | "PRINT_ON_DEMAND",
    }));
  }

  return [
    {
      id: `v-${s.id}-a`,
      master_sku: `${s.sku}-${s.colorCode}-M`,
      size: "M",
      color: {
        id: `c-${s.colorCode.toLowerCase()}`,
        color_name: s.colorName,
        hex: s.hex,
        filament_sku: `FIL-${(s.material || "PLA").toUpperCase()}-${s.colorCode}-01`,
        printer_profile: "pla-standard-0.2",
        stock_material: s.material || "PLA",
      },
      price_cents: s.price,
      personalization_price_cents: s.persoPrice,
      available_stock: stock,
      production_capacity: 40,
      safety_stock: 5,
      mode: s.mode || "PRINT_ON_DEMAND",
    },
    {
      id: `v-${s.id}-b`,
      master_sku: `${s.sku}-INK-M`,
      size: "M",
      color: {
        id: "c-ink",
        color_name: "Ink",
        hex: "#0B0B0F",
        filament_sku: "FIL-PLA-INK-01",
        printer_profile: "pla-standard-0.2",
        stock_material: "PLA",
      },
      price_cents: s.price,
      personalization_price_cents: s.persoPrice,
      available_stock: 0,
      production_capacity: 40,
      safety_stock: 5,
      mode: "PRINT_ON_DEMAND",
    },
  ];
}

function seedToProduct(s: Seed): CatalogProduct {
  const stock = s.mode === "IN_STOCK" ? 18 : 0;
  const skuImg = `/products/${s.sku.toLowerCase()}.png`;
  return {
    id: s.id,
    slug: s.slug,
    status: "ACTIVE",
    group: s.group,
    vibes: s.vibes,
    category_id: s.category_id,
    subcategory_id: s.subcategory_id,
    license_id: "lic-own-001",
    name: s.name,
    description: s.description,
    why: s.why,
    drop_label: s.drop ?? null,
    limited_units: s.drop === "LIMITED" ? 80 : null,
    personalizable: s.personalizable,
    personalization_fields: s.fields,
    images: s.images?.length ? s.images : [skuImg],
    dimensions: s.dims,
    weight_g: s.weight_g,
    care: {
      de: "Trocken halten. Innenbereich. Nicht spülen.",
      en: "Keep dry. Indoor use. Do not dishwasher.",
    },
    included: s.included ?? {
      de: `1× ${s.name.de}`,
      en: `1× ${s.name.en}`,
    },
    finish: "Matte / satin",
    production: {
      file_version: `${s.sku}_MASTER_v1`,
      printer_type: "Bambu P1S",
      material: s.material || "PLA",
      grams_required: s.grams,
      estimated_print_minutes: s.minutes,
      post_process_minutes: 8,
      quality_check_required: true,
      packaging_sku: s.grams > 80 ? "PKG-MD-02" : "PKG-SM-01",
      stl_master_sku: s.sku,
    },
    compliance: {
      ...baseCompliance,
      product_identifier: s.sku,
      product_class: s.product_class,
      material: s.material || "PLA",
    },
    variants: variantsForSeed(s, stock),
    for_sale: true,
  };
}

/** Batch 01 — 20 bestsellers inspired by Etsy/MakerWorld demand (own geometry). */
const seeds: Seed[] = [
  {
    id: "p-name-key",
    slug: "name-keychain",
    sku: "PL-NAME-KEY",
    category_id: "cat-personalized",
    subcategory_id: "sub-keychains",
    group: "HERO",
    vibes: ["GIFTS", "CUSTOM", "PLAY"],
    name: { de: "Name Schlüsselanhänger", en: "Name Keychain" },
    description: {
      de: "Bubble-Name mit Kontrastfarbe: dein Name als robuster 3D-Druck-Anhänger inkl. Metallring — für Schlüsselbund, Rucksack oder Koffer. Persönliches Geschenk in Minuten.",
      en: "Bubble-name with high contrast: your name as a sturdy 3D-printed tag with metal ring — for keys, backpack or luggage. A personal gift in minutes.",
    },
    why: {
      de: "Zweifarbig, klar lesbar, sofort persönlich — der Alltags-Bestseller.",
      en: "Two-tone, easy to read, instantly personal — everyday bestseller.",
    },
    fields: ["name", "color"],
    personalizable: true,
    dims: "ca. 45–70 × 22 × 5 mm (je nach Name)",
    weight_g: 10,
    grams: 8,
    minutes: 32,
    price: 1290,
    persoPrice: 0,
    product_class: "ACCESSORY",
    drop: "NEW DROP",
    hex: "#6B2D9B",
    colorName: "Violet / White",
    colorCode: "VIO",
    mode: "IN_STOCK",
    images: ["/products/pl-name-key.png", "/products/pl-name-key-2.png"],
    included: {
      de: "1× personalisierter Name-Anhänger + 1× Metall-Splitring (25 mm)",
      en: "1× personalized name tag + 1× metal split ring (25 mm)",
    },
  },
  {
    id: "p-bag-tag",
    slug: "rucksack-tag",
    sku: "PL-BAG-TAG",
    category_id: "cat-kids",
    subcategory_id: "sub-school-tags",
    group: "HERO",
    vibes: ["GIFTS", "CUSTOM"],
    name: { de: "Rucksack-Tag", en: "Backpack Tag" },
    description: {
      de: "Schulranzen-Anhänger mit Name — findet man im Chaos der Garderobe.",
      en: "School bag tag with name — easy to spot in the cloakroom chaos.",
    },
    why: { de: "Eltern-Liebling. Klare Lesbarkeit.", en: "Parent favorite. Clear readability." },
    fields: ["name", "color"],
    personalizable: true,
    dims: "55 × 35 × 3 mm",
    weight_g: 12,
    grams: 10,
    minutes: 35,
    price: 1490,
    persoPrice: 0,
    product_class: "ACCESSORY",
    hex: "#C8FF3D",
    colorName: "Acid Lime",
    colorCode: "LIM",
  },
  {
    id: "p-flexi-dino",
    slug: "flexi-dino",
    sku: "PL-FLEXI-DINO",
    category_id: "cat-play",
    subcategory_id: "sub-flexi",
    group: "HERO",
    vibes: ["PLAY", "GIFTS"],
    name: { de: "Flexi Dino", en: "Flexi Dino" },
    description: {
      de: "Gelenkiger Dino — print-in-place Feeling, Desk- & Regal-Star.",
      en: "Articulated dino — print-in-place vibe, desk & shelf star.",
    },
    why: { de: "Bewegung verkauft sich. Ideal als Geschenk.", en: "Motion sells. Ideal gift." },
    fields: ["color"],
    personalizable: false,
    dims: "90 × 30 × 25 mm",
    weight_g: 28,
    grams: 24,
    minutes: 95,
    price: 2190,
    persoPrice: 0,
    product_class: "COLLECTIBLE",
    drop: "NEW DROP",
    hex: "#FF5A3C",
    colorName: "Hot Coral",
    colorCode: "COR",
    mode: "IN_STOCK",
  },
  {
    id: "p-clicker",
    slug: "fidget-clicker",
    sku: "PL-CLICKER",
    category_id: "cat-play",
    subcategory_id: "sub-clicker",
    group: "EVERGREEN",
    vibes: ["PLAY", "DESK", "GIFTS"],
    name: { de: "Fidget Clicker", en: "Fidget Clicker" },
    description: {
      de: "Print-in-place Clicker — leise genug fürs Büro, süchtig genug fürs Sofa.",
      en: "Print-in-place clicker — quiet enough for the office, addictive on the sofa.",
    },
    why: { de: "Viral auf MakerWorld — wir haben unser Original.", en: "Viral category — our original take." },
    fields: ["color"],
    personalizable: false,
    dims: "35 × 35 × 18 mm",
    weight_g: 14,
    grams: 12,
    minutes: 45,
    price: 1590,
    persoPrice: 0,
    product_class: "ACCESSORY",
    hex: "#0B0B0F",
    colorName: "Ink",
    colorCode: "INK",
    mode: "IN_STOCK",
  },
  {
    id: "p-pen-cup",
    slug: "desk-pen-cup",
    sku: "PL-PEN-CUP",
    category_id: "cat-desk",
    subcategory_id: "sub-organizer",
    group: "EVERGREEN",
    vibes: ["DESK", "GIFTS", "ROOM"],
    name: { de: "Desk Pen Cup", en: "Desk Pen Cup" },
    description: {
      de: "Stifteköcher mit klarer Silhouette — Setup sieht sofort aufgeräumt aus.",
      en: "Pen cup with a clear silhouette — setup looks tidy instantly.",
    },
    why: { de: "Alltagstauglich + Geschenk fürs Büro.", en: "Everyday useful + office gift." },
    fields: ["color", "initials"],
    personalizable: true,
    dims: "70 × 70 × 90 mm",
    weight_g: 68,
    grams: 55,
    minutes: 140,
    price: 2490,
    persoPrice: 400,
    product_class: "ACCESSORY",
    hex: "#E8E4DA",
    colorName: "Mist",
    colorCode: "MST",
    material: "PETG",
  },
  {
    id: "p-orbit-clip",
    slug: "orbit-cable-clip",
    sku: "PL-ORBIT-CLIP",
    category_id: "cat-desk",
    subcategory_id: "sub-cables",
    group: "DROP",
    vibes: ["DESK", "ROOM", "GIFTS"],
    name: { de: "Orbit Cable Clip", en: "Orbit Cable Clip" },
    description: {
      de: "Drei Kabel. Ein Orbit. Limitierte Charge.",
      en: "Three cables. One orbit. Limited batch.",
    },
    why: { de: "Klein, sichtbar, sofort nützlich.", en: "Small, visible, instantly useful." },
    fields: ["color"],
    personalizable: false,
    dims: "50 × 30 × 20 mm",
    weight_g: 16,
    grams: 14,
    minutes: 40,
    price: 1290,
    persoPrice: 0,
    product_class: "ACCESSORY",
    drop: "LIMITED",
    hex: "#C8FF3D",
    colorName: "Acid Lime",
    colorCode: "LIM",
    mode: "IN_STOCK",
  },
  {
    id: "p-phone-stand",
    slug: "phone-stand",
    sku: "PL-PHONE-STAND",
    category_id: "cat-desk",
    subcategory_id: "sub-stands",
    group: "EVERGREEN",
    vibes: ["DESK", "GIFTS", "CUSTOM"],
    name: { de: "Phone Stand", en: "Phone Stand" },
    description: {
      de: "Stabiler Handyhalter für Desk, Küche, Stream — optional mit Initialen.",
      en: "Stable phone stand for desk, kitchen, stream — optional initials.",
    },
    why: { de: "Täglicher Nutzen = Wiederbestellung.", en: "Daily use = reorders." },
    fields: ["initials", "color"],
    personalizable: true,
    dims: "80 × 70 × 60 mm",
    weight_g: 48,
    grams: 42,
    minutes: 110,
    price: 1990,
    persoPrice: 350,
    product_class: "ACCESSORY",
    hex: "#7B61FF",
    colorName: "Signal Violet",
    colorCode: "VIO",
  },
  {
    id: "p-desk-arc",
    slug: "desk-arc-stand",
    sku: "PL-DESK-ARC",
    category_id: "cat-desk",
    subcategory_id: "sub-stands",
    group: "EVERGREEN",
    vibes: ["DESK", "GAMING", "CUSTOM"],
    name: { de: "Desk Arc Stand", en: "Desk Arc Stand" },
    description: {
      de: "Kopfhörer + Controller. Ein Bogen. Null Chaos.",
      en: "Headphones + controller. One arc. Zero chaos.",
    },
    why: { de: "Setup-Upgrade, das man sieht.", en: "A setup upgrade you can see." },
    fields: ["color", "size", "initials"],
    personalizable: true,
    dims: "180 × 40 × 120 mm",
    weight_g: 160,
    grams: 140,
    minutes: 280,
    price: 3490,
    persoPrice: 600,
    product_class: "ACCESSORY",
    hex: "#E8E4DA",
    colorName: "Mist",
    colorCode: "MST",
    material: "PETG",
  },
  {
    id: "p-name-ridge",
    slug: "name-ridge",
    sku: "PL-NAME-RIDGE",
    category_id: "cat-personalized",
    subcategory_id: "sub-nameplates",
    group: "EVERGREEN",
    vibes: ["CUSTOM", "GIFTS", "ROOM"],
    name: { de: "Name Ridge", en: "Name Ridge" },
    description: {
      de: "Name als Regalobjekt — kein billiges Schild.",
      en: "Your name as a shelf object — not a cheap sign.",
    },
    why: { de: "Personalisierung mit Produktgefühl.", en: "Personalization that feels premium." },
    fields: ["name", "color", "size"],
    personalizable: true,
    dims: "bis 120 mm Breite",
    weight_g: 42,
    grams: 38,
    minutes: 100,
    price: 2490,
    persoPrice: 0,
    product_class: "DECORATION",
    hex: "#0B0B0F",
    colorName: "Ink",
    colorCode: "INK",
  },
  {
    id: "p-lith-frame",
    slug: "lithophane-frame",
    sku: "PL-LITH-FRAME",
    category_id: "cat-home",
    subcategory_id: "sub-lamps",
    group: "HERO",
    vibes: ["GIFTS", "CUSTOM", "ROOM"],
    name: { de: "Lithophane Rahmen", en: "Lithophane Frame" },
    description: {
      de: "Rahmen für Foto-Lithophane — Licht macht das Motiv sichtbar.",
      en: "Frame for photo lithophanes — light reveals the image.",
    },
    why: { de: "Premium-Geschenk mit Wow-Effekt.", en: "Premium gift with wow factor." },
    fields: ["text", "color"],
    personalizable: true,
    dims: "100 × 10 × 130 mm",
    weight_g: 55,
    grams: 48,
    minutes: 160,
    price: 2990,
    persoPrice: 800,
    product_class: "DECORATION",
    drop: "NEW DROP",
    hex: "#FFE600",
    colorName: "Feast Yellow",
    colorCode: "YEL",
  },
  {
    id: "p-mini-pot",
    slug: "mini-planter",
    sku: "PL-MINI-POT",
    category_id: "cat-home",
    subcategory_id: "sub-plants",
    group: "EVERGREEN",
    vibes: ["ROOM", "GIFTS"],
    name: { de: "Mini Planter", en: "Mini Planter" },
    description: {
      de: "Kleiner Übertopf für Sukkulenten & Schreibtischgrün.",
      en: "Small planter for succulents & desk greenery.",
    },
    why: { de: "Home-Trend + schneller Druck.", en: "Home trend + fast print." },
    fields: ["color"],
    personalizable: false,
    dims: "75 × 75 × 70 mm",
    weight_g: 52,
    grams: 45,
    minutes: 130,
    price: 1890,
    persoPrice: 0,
    product_class: "DECORATION",
    hex: "#FF5A3C",
    colorName: "Hot Coral",
    colorCode: "COR",
  },
  {
    id: "p-heart-box",
    slug: "heart-gift-box",
    sku: "PL-HEART-BOX",
    category_id: "cat-occasions",
    subcategory_id: "sub-wedding",
    group: "EVERGREEN",
    vibes: ["GIFTS", "CUSTOM"],
    name: { de: "Herz Geschenkbox", en: "Heart Gift Box" },
    description: {
      de: "Kleine Herzbox für Ringe, Notizen, Party Favors.",
      en: "Small heart box for rings, notes, party favors.",
    },
    why: { de: "Hochzeit & Valentinstag — starke Saison.", en: "Wedding & Valentine — strong season." },
    fields: ["initials", "color"],
    personalizable: true,
    dims: "70 × 65 × 35 mm",
    weight_g: 36,
    grams: 30,
    minutes: 95,
    price: 1790,
    persoPrice: 400,
    product_class: "ACCESSORY",
    hex: "#FF5A3C",
    colorName: "Hot Coral",
    colorCode: "COR",
  },
  {
    id: "p-cake-top",
    slug: "cake-topper-name",
    sku: "PL-CAKE-TOP",
    category_id: "cat-occasions",
    subcategory_id: "sub-birthday",
    group: "HERO",
    vibes: ["GIFTS", "CUSTOM"],
    name: { de: "Cake Topper Name", en: "Name Cake Topper" },
    description: {
      de: "Tortenstecker mit Name — Geburtstag in Minuten personalisiert.",
      en: "Cake topper with name — birthday personalization in minutes.",
    },
    why: { de: "Event-Bestseller mit klarer Deadline.", en: "Event bestseller with clear deadline." },
    fields: ["name", "color"],
    personalizable: true,
    dims: "100 × 8 × 120 mm",
    weight_g: 18,
    grams: 15,
    minutes: 55,
    price: 1690,
    persoPrice: 0,
    product_class: "DECORATION",
    drop: "NEW DROP",
    hex: "#FFE600",
    colorName: "Feast Yellow",
    colorCode: "YEL",
  },
  {
    id: "p-ornament",
    slug: "deko-ornament",
    sku: "PL-ORNAMENT",
    category_id: "cat-personalized",
    subcategory_id: "sub-ornaments",
    group: "EVERGREEN",
    vibes: ["GIFTS", "CUSTOM", "ROOM"],
    name: { de: "Deko Ornament", en: "Decor Ornament" },
    description: {
      de: "Anhänger mit Text/Initialen — Baum, Geschenk, Fenster.",
      en: "Ornament with text/initials — tree, gift, window.",
    },
    why: { de: "Saisonal stark, ganzjährig verschenkbar.", en: "Seasonally strong, giftable all year." },
    fields: ["initials", "text", "color"],
    personalizable: true,
    dims: "60 × 10 × 70 mm",
    weight_g: 16,
    grams: 14,
    minutes: 50,
    price: 1490,
    persoPrice: 300,
    product_class: "DECORATION",
    hex: "#C8FF3D",
    colorName: "Acid Lime",
    colorCode: "LIM",
  },
  {
    id: "p-pet-tag",
    slug: "haustier-marke",
    sku: "PL-PET-TAG",
    category_id: "cat-occasions",
    subcategory_id: "sub-pets",
    group: "EVERGREEN",
    vibes: ["GIFTS", "CUSTOM"],
    name: { de: "Haustier-Marke", en: "Pet Tag" },
    description: {
      de: "Leichte Halsband-Marke mit Name — kein Metallklappern.",
      en: "Light collar tag with name — no metal clank.",
    },
    why: { de: "Emotionale Käufe, hohe Personalisierung.", en: "Emotional purchases, high personalization." },
    fields: ["name", "color"],
    personalizable: true,
    dims: "40 × 30 × 3 mm",
    weight_g: 6,
    grams: 5,
    minutes: 22,
    price: 1190,
    persoPrice: 0,
    product_class: "ACCESSORY",
    hex: "#7B61FF",
    colorName: "Signal Violet",
    colorCode: "VIO",
  },
  {
    id: "p-bookmark",
    slug: "lesezeichen-name",
    sku: "PL-BOOKMARK",
    category_id: "cat-kids",
    subcategory_id: "sub-bookmarks",
    group: "EVERGREEN",
    vibes: ["GIFTS", "CUSTOM"],
    name: { de: "Lesezeichen Name", en: "Name Bookmark" },
    description: {
      de: "Flaches Lesezeichen mit Name — Schule, Buchclub, Geschenk.",
      en: "Flat bookmark with name — school, book club, gift.",
    },
    why: { de: "Schnell gedruckt, stark personalisiert.", en: "Fast to print, highly personalized." },
    fields: ["name", "color"],
    personalizable: true,
    dims: "140 × 30 × 2 mm",
    weight_g: 8,
    grams: 6,
    minutes: 30,
    price: 990,
    persoPrice: 0,
    product_class: "ACCESSORY",
    hex: "#0B0B0F",
    colorName: "Ink",
    colorCode: "INK",
  },
  {
    id: "p-hex-hook",
    slug: "hex-wandhaken",
    sku: "PL-HEX-HOOK",
    category_id: "cat-home",
    subcategory_id: "sub-hooks",
    group: "EVERGREEN",
    vibes: ["ROOM", "GIFTS"],
    name: { de: "Hex Wandhaken", en: "Hex Wall Hook" },
    description: {
      de: "Geometrischer Haken für Jacken, Keys, Handtücher (leichte Last).",
      en: "Geometric hook for jackets, keys, towels (light load).",
    },
    why: { de: "Home-Upgrade ohne Bohren-Drama (mit Klebe-Pad).", en: "Home upgrade without drill drama." },
    fields: ["color"],
    personalizable: false,
    dims: "50 × 30 × 40 mm",
    weight_g: 22,
    grams: 18,
    minutes: 60,
    price: 1390,
    persoPrice: 0,
    product_class: "ACCESSORY",
    hex: "#E8E4DA",
    colorName: "Mist",
    colorCode: "MST",
    material: "PETG",
  },
  {
    id: "p-soap-dish",
    slug: "seifenschale",
    sku: "PL-SOAP-DISH",
    category_id: "cat-home",
    subcategory_id: "sub-hooks",
    group: "EVERGREEN",
    vibes: ["ROOM", "GIFTS"],
    name: { de: "Seifenschale", en: "Soap Dish" },
    description: {
      de: "Abfluss-freundliche Schale — Bad & Küche, PETG-ready.",
      en: "Drain-friendly dish — bath & kitchen, PETG-ready.",
    },
    why: { de: "Nützlich + schön = Geschenk ohne Risiko.", en: "Useful + pretty = low-risk gift." },
    fields: ["color"],
    personalizable: false,
    dims: "110 × 70 × 15 mm",
    weight_g: 38,
    grams: 32,
    minutes: 85,
    price: 1590,
    persoPrice: 0,
    product_class: "ACCESSORY",
    hex: "#C8FF3D",
    colorName: "Acid Lime",
    colorCode: "LIM",
    material: "PETG",
  },
  {
    id: "p-ctrl-stand",
    slug: "controller-stand",
    sku: "PL-CTRL-STAND",
    category_id: "cat-desk",
    subcategory_id: "sub-stands",
    group: "EVERGREEN",
    vibes: ["GAMING", "DESK", "GIFTS"],
    name: { de: "Controller Stand", en: "Controller Stand" },
    description: {
      de: "Halter für Gamepad — Setup wirkt sofort teurer.",
      en: "Gamepad stand — setup looks premium instantly.",
    },
    why: { de: "Gaming-Geschenk mit Display-Effekt.", en: "Gaming gift with display effect." },
    fields: ["color", "initials"],
    personalizable: true,
    dims: "120 × 80 × 70 mm",
    weight_g: 95,
    grams: 80,
    minutes: 200,
    price: 2790,
    persoPrice: 450,
    product_class: "ACCESSORY",
    hex: "#0B0B0F",
    colorName: "Ink",
    colorCode: "INK",
  },
  {
    id: "p-flex-coil",
    slug: "flex-coil",
    sku: "PL-FLEX-COIL",
    category_id: "cat-play",
    subcategory_id: "sub-flexi",
    group: "HERO",
    vibes: ["PLAY", "DESK", "GIFTS"],
    name: { de: "Flex Coil", en: "Flex Coil" },
    description: {
      de: "Endlos drehbares Desk-Objekt. Leise. Suchtig.",
      en: "Endless twist desk object. Quiet. Addictive.",
    },
    why: { de: "Liegt gut in der Hand — Statement auf dem Setup.", en: "Feels right — tiny statement on any setup." },
    fields: ["color", "name"],
    personalizable: true,
    dims: "70 × 45 × 45 mm",
    weight_g: 40,
    grams: 36,
    minutes: 90,
    price: 1890,
    persoPrice: 400,
    product_class: "ACCESSORY",
    drop: "NEW DROP",
    hex: "#FFE600",
    colorName: "Feast Yellow",
    colorCode: "YEL",
    mode: "IN_STOCK",
  },
];

export const batch01Products: CatalogProduct[] = seeds.map(seedToProduct);
