/**
 * Gift-safe trend seeds from MakerWorld / market research (titles & categories only).
 * Never copy STL/geometry or third-party photos — OWN listing concepts only.
 */
export type TrendHint = {
  kind: string;
  labelDe: string;
  labelEn: string;
  category_id: string;
  subcategory_id: string;
  vibes: Array<"PLAY" | "DESK" | "ROOM" | "GAMING" | "GIFTS" | "CUSTOM">;
  personalizable: boolean;
  fields: Array<"name" | "initials" | "text" | "color" | "size">;
  photoKind: string;
  priceCents: number;
  grams: number;
  minutes: number;
  dims: string;
};

/** Hot categories observed on MakerWorld Trending (gift / desk / play filter). */
export const TRENDING_HINTS: TrendHint[] = [
  {
    kind: "name-keychain-bubble",
    labelDe: "Bubble Name Schlüsselanhänger",
    labelEn: "Bubble Name Keychain",
    category_id: "cat-personalized",
    subcategory_id: "sub-keychains",
    vibes: ["GIFTS", "CUSTOM", "PLAY"],
    personalizable: true,
    fields: ["name", "color"],
    photoKind: "keychain",
    priceCents: 1290,
    grams: 8,
    minutes: 30,
    dims: "45–70 × 22 × 5 mm",
  },
  {
    kind: "gear-fidget-key",
    labelDe: "Mini Getriebe Fidget-Anhänger",
    labelEn: "Mini Gearbox Fidget Keychain",
    category_id: "cat-play",
    subcategory_id: "sub-clicker",
    vibes: ["PLAY", "GIFTS", "DESK"],
    personalizable: false,
    fields: ["color"],
    photoKind: "clicker",
    priceCents: 1490,
    grams: 12,
    minutes: 40,
    dims: "35 × 25 × 12 mm",
  },
  {
    kind: "gyro-spinner-key",
    labelDe: "Gyro Spinner Schlüsselanhänger",
    labelEn: "Gyro Spinner Keychain",
    category_id: "cat-play",
    subcategory_id: "sub-clicker",
    vibes: ["PLAY", "GIFTS"],
    personalizable: true,
    fields: ["initials", "color"],
    photoKind: "clicker",
    priceCents: 1590,
    grams: 14,
    minutes: 45,
    dims: "50 × 50 × 10 mm",
  },
  {
    kind: "name-desk-organizer",
    labelDe: "Name Desk Organizer",
    labelEn: "Name Desk Organizer",
    category_id: "cat-desk",
    subcategory_id: "sub-organizer",
    vibes: ["DESK", "CUSTOM", "GIFTS"],
    personalizable: true,
    fields: ["name", "color"],
    photoKind: "cup",
    priceCents: 2490,
    grams: 55,
    minutes: 120,
    dims: "120 × 80 × 90 mm",
  },
  {
    kind: "filament-clip",
    labelDe: "Filament Clip Set",
    labelEn: "Filament Clip Set",
    category_id: "cat-desk",
    subcategory_id: "sub-cables",
    vibes: ["DESK", "GIFTS"],
    personalizable: false,
    fields: ["color"],
    photoKind: "orbit",
    priceCents: 990,
    grams: 6,
    minutes: 20,
    dims: "30 × 20 × 12 mm",
  },
  {
    kind: "pen-holder-ninja",
    labelDe: "Charakter Stiftehalter",
    labelEn: "Character Pen Holder",
    category_id: "cat-desk",
    subcategory_id: "sub-organizer",
    vibes: ["DESK", "GIFTS", "PLAY"],
    personalizable: true,
    fields: ["name", "color"],
    photoKind: "cup",
    priceCents: 2290,
    grams: 48,
    minutes: 110,
    dims: "90 × 70 × 110 mm",
  },
  {
    kind: "phone-stand-arc",
    labelDe: "Phone Stand Arc",
    labelEn: "Phone Stand Arc",
    category_id: "cat-desk",
    subcategory_id: "sub-stands",
    vibes: ["DESK", "GIFTS"],
    personalizable: true,
    fields: ["initials", "color"],
    photoKind: "phone",
    priceCents: 1890,
    grams: 35,
    minutes: 75,
    dims: "90 × 70 × 80 mm",
  },
  {
    kind: "watch-stand",
    labelDe: "Uhrenständer",
    labelEn: "Watch Stand",
    category_id: "cat-desk",
    subcategory_id: "sub-stands",
    vibes: ["DESK", "GIFTS", "ROOM"],
    personalizable: true,
    fields: ["initials", "color"],
    photoKind: "arc",
    priceCents: 1990,
    grams: 40,
    minutes: 90,
    dims: "80 × 60 × 70 mm",
  },
  {
    kind: "flexi-dragon-egg",
    labelDe: "Flexi Drachen-Ei Fidget",
    labelEn: "Flexi Dragon Egg Fidget",
    category_id: "cat-play",
    subcategory_id: "sub-flexi",
    vibes: ["PLAY", "GIFTS"],
    personalizable: false,
    fields: ["color"],
    photoKind: "dino",
    priceCents: 1690,
    grams: 22,
    minutes: 55,
    dims: "55 × 40 × 40 mm",
  },
  {
    kind: "flexi-fabric",
    labelDe: "Flexi Stoff-Fidget",
    labelEn: "Flexi Fabric Fidget",
    category_id: "cat-play",
    subcategory_id: "sub-flexi",
    vibes: ["PLAY", "DESK", "GIFTS"],
    personalizable: false,
    fields: ["color"],
    photoKind: "coil",
    priceCents: 1490,
    grams: 18,
    minutes: 50,
    dims: "80 × 40 × 8 mm",
  },
  {
    kind: "money-vault",
    labelDe: "Print-in-Place Spardose",
    labelEn: "Print-in-Place Money Vault",
    category_id: "cat-home",
    subcategory_id: "sub-hooks",
    vibes: ["ROOM", "GIFTS", "PLAY"],
    personalizable: true,
    fields: ["name", "color"],
    photoKind: "heart",
    priceCents: 2190,
    grams: 70,
    minutes: 150,
    dims: "100 × 80 × 80 mm",
  },
  {
    kind: "hearty-planter",
    labelDe: "Herz Hände Mini-Topf",
    labelEn: "Heart Hands Mini Planter",
    category_id: "cat-home",
    subcategory_id: "sub-plants",
    vibes: ["ROOM", "GIFTS"],
    personalizable: false,
    fields: ["color"],
    photoKind: "pot",
    priceCents: 1790,
    grams: 45,
    minutes: 95,
    dims: "85 × 70 × 75 mm",
  },
  {
    kind: "hat-hook-wall",
    labelDe: "Wand-Hutablage",
    labelEn: "Wall Hat Holder",
    category_id: "cat-home",
    subcategory_id: "sub-hooks",
    vibes: ["ROOM", "GIFTS"],
    personalizable: false,
    fields: ["color"],
    photoKind: "hook",
    priceCents: 1590,
    grams: 28,
    minutes: 60,
    dims: "120 × 40 × 50 mm",
  },
  {
    kind: "desktop-bin",
    labelDe: "Desktop Mülleimer Mini",
    labelEn: "Desktop Trash Bin",
    category_id: "cat-desk",
    subcategory_id: "sub-organizer",
    vibes: ["DESK", "GIFTS"],
    personalizable: true,
    fields: ["initials", "color"],
    photoKind: "cup",
    priceCents: 1690,
    grams: 40,
    minutes: 80,
    dims: "90 × 90 × 100 mm",
  },
  {
    kind: "seasonal-ornament",
    labelDe: "Minimal Baum-Ornament",
    labelEn: "Minimal Tree Ornament",
    category_id: "cat-personalized",
    subcategory_id: "sub-ornaments",
    vibes: ["GIFTS", "CUSTOM", "ROOM"],
    personalizable: true,
    fields: ["name", "color"],
    photoKind: "ornament",
    priceCents: 1190,
    grams: 10,
    minutes: 35,
    dims: "70 × 50 × 4 mm",
  },
  {
    kind: "ghost-balloon",
    labelDe: "Cute Ghost Deko",
    labelEn: "Cute Ghost Decor",
    category_id: "cat-home",
    subcategory_id: "sub-lamps",
    vibes: ["ROOM", "GIFTS", "PLAY"],
    personalizable: false,
    fields: ["color"],
    photoKind: "ornament",
    priceCents: 1390,
    grams: 16,
    minutes: 40,
    dims: "60 × 45 × 40 mm",
  },
  {
    kind: "wobbly-penguin",
    labelDe: "Wackel-Pinguin",
    labelEn: "Wobbly Penguin",
    category_id: "cat-play",
    subcategory_id: "sub-flexi",
    vibes: ["PLAY", "GIFTS"],
    personalizable: false,
    fields: ["color"],
    photoKind: "dino",
    priceCents: 1590,
    grams: 20,
    minutes: 50,
    dims: "50 × 40 × 55 mm",
  },
  {
    kind: "cake-topper-bday",
    labelDe: "Birthday Cake Topper",
    labelEn: "Birthday Cake Topper",
    category_id: "cat-occasions",
    subcategory_id: "sub-birthday",
    vibes: ["GIFTS", "CUSTOM"],
    personalizable: true,
    fields: ["name", "text", "color"],
    photoKind: "cake",
    priceCents: 1490,
    grams: 12,
    minutes: 40,
    dims: "120 × 80 × 3 mm",
  },
  {
    kind: "pet-tag-bone",
    labelDe: "Haustier Namens-Tag",
    labelEn: "Pet Name Tag",
    category_id: "cat-occasions",
    subcategory_id: "sub-pets",
    vibes: ["GIFTS", "CUSTOM"],
    personalizable: true,
    fields: ["name", "color"],
    photoKind: "pet",
    priceCents: 1290,
    grams: 8,
    minutes: 28,
    dims: "40 × 25 × 3 mm",
  },
  {
    kind: "bookmark-name",
    labelDe: "Name Lesezeichen",
    labelEn: "Name Bookmark",
    category_id: "cat-kids",
    subcategory_id: "sub-bookmarks",
    vibes: ["GIFTS", "CUSTOM"],
    personalizable: true,
    fields: ["name", "color"],
    photoKind: "bookmark",
    priceCents: 990,
    grams: 6,
    minutes: 22,
    dims: "140 × 35 × 2 mm",
  },
  {
    kind: "joystick-keycap",
    labelDe: "Joystick Keycap",
    labelEn: "Joystick Keycap",
    category_id: "cat-desk",
    subcategory_id: "sub-stands",
    vibes: ["GAMING", "DESK", "GIFTS"],
    personalizable: false,
    fields: ["color"],
    photoKind: "clicker",
    priceCents: 890,
    grams: 4,
    minutes: 18,
    dims: "18 × 18 × 12 mm",
  },
  {
    kind: "toothpaste-squeezer",
    labelDe: "Zahnpasta-Ausdrücker",
    labelEn: "Toothpaste Squeezer",
    category_id: "cat-home",
    subcategory_id: "sub-hooks",
    vibes: ["ROOM", "GIFTS"],
    personalizable: false,
    fields: ["color"],
    photoKind: "soap",
    priceCents: 1190,
    grams: 15,
    minutes: 35,
    dims: "70 × 40 × 25 mm",
  },
  {
    kind: "caliper-ruler",
    labelDe: "Mini Messschieber Lineal",
    labelEn: "Mini Caliper Ruler",
    category_id: "cat-desk",
    subcategory_id: "sub-organizer",
    vibes: ["DESK", "GIFTS"],
    personalizable: true,
    fields: ["initials", "color"],
    photoKind: "ridge",
    priceCents: 1390,
    grams: 12,
    minutes: 40,
    dims: "120 × 25 × 8 mm",
  },
  {
    kind: "business-card-stand",
    labelDe: "Visitenkarten-Ständer",
    labelEn: "Business Card Stand",
    category_id: "cat-desk",
    subcategory_id: "sub-organizer",
    vibes: ["DESK", "GIFTS", "CUSTOM"],
    personalizable: true,
    fields: ["name", "color"],
    photoKind: "ridge",
    priceCents: 1590,
    grams: 22,
    minutes: 55,
    dims: "90 × 50 × 40 mm",
  },
];

/** Brand / franchise strings we refuse to list (IP risk). */
export const BLOCKED_IP = [
  "pokemon",
  "pokeball",
  "charizard",
  "disney",
  "marvel",
  "spider",
  "spidey",
  "grinch",
  "porsche",
  "ferrari",
  "nike",
  "adidas",
  "lego",
  "star wars",
  "batman",
  "hello kitty",
  "minecraft",
  "fortnite",
  "harry potter",
  "barbie",
];

export function isIpSafe(text: string) {
  const t = text.toLowerCase();
  return !BLOCKED_IP.some((b) => t.includes(b));
}
